version: '3.7'
services:
    app:
        container_name: dbs-frontend
        build:
            context: .
            args:
                - STAGE=dev
            dockerfile: Dockerfile
        ports:
            - '3000:80'
