const API_END_POINTS = {
    AUTH: '/auth',
    USERS: '/users',
    OTP: '/otp',
    GENERATE: '/generate',
    VALIDATE: '/validate',
    REFRESH: '/refresh',
    OFFSET: '?offset=',
    LIMIT: '&limit=',
    SEARCH: '?search=',
    VEHICLE_TYPES: '/vehicle-types',
    VEHICLE_MODELS: '/vehicle-models',
    RIM_SIZES: '/rim-sizes',
    SUB_CATEGORY_PRICES: '/sub-category-prices',
    ALL: '/all',
    JOB_CARDS: '/job-cards',
    VEHICLES: '/vehicles',
    JOB_CARD_ITEMS: '/job-card-items',
    BRANCH: '/branch',
    ITEMS: '/items',
    EMPLOYEES: '/employees',
    STATUS: '/status',
    PAUSE: '/pause',
    RESUME: '/resume',
    GENERATE_BILL: '/generatebill',
    ADD_OTHER_ITEMS: '/job-card-additional-items',
    JOB_CARD_DISCOUNTS: '/job-card-discounts',
    PAY: '/pay',
    BRANCHES: '/branches',
    CITIES: '/cities',
    COUNTRIES: '/countries',
    OVERVIEW: '/overview',
    START_DATE: '?startDate=',
    END_DATE: '&endDate=',
    BRANCH_ID: 'branchId=',
    VEHICLE_BRAND: '/vehicle-brands',
    CATEGORIES: '/categories',
    SUB_CATEGORIES: '/sub-categories',
};

enum API_METHODS {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    PATCH = 'PATCH',
    DELETE = 'DELETE',
}

export { API_END_POINTS, API_METHODS };
